### PR TITLE
Removed popping of filter params in choices

### PR DESCRIPTION
**Pull request by annamalaissh**

### CODE REVIEW

**Comment by simon-online** [comment]
I don't think this pull request should be merged as the code changes don't seem to fix the issue of the date range filter being cleared when another filter is selected, from the testing that I have done.

**Comment by annamalaissh** [comment]
@simon-online : yes you are right, i fixed the issue by some monkey patching in the django admin get params. However i am yet to find a solution for this issue at the app level.

**Comment by simon-online** [comment]
I believe that this suggested code change solves the problem:
https://github.com/tzulberti/django-datefilterspec/pull/11#issuecomment-190688172

**Comment by annamalaissh** [comment]
@simon-online  Thanks, i will try that code suggestion, i am unable to delete my PR here.

**Pull request closed without merging**
