### PR TITLE
reset fix

### PR DESCRIPTION
**Pull request by m3ck0**
as mentioned in code comments, reset functionality, after submitting date range, is not working, which is some kind of bug (maybe). So implemented little js to fix this issue.

### CODE REVIEW

**Review by yeago — COMMENTED** [review]
Was it just never implemented?

**Comment by Jambazishvili** [comment]
sorry, can't really get the question?

**Comment by yeago** [comment]
Well the reset button has been the a while, and this is an additive PR. Did it simply have no functionality behind it previously?

**Comment by Jambazishvili** [comment]
previously it had no functionality once, you click filter, based on dates. So since it cleans up fields before user submits date, I think the clear button should also clean the fields after filtering queryset (that's my point of view)

**Comment by Jambazishvili** [comment]
are you going to approve my update, or just ignore it?

**Comment by yeago** [comment]
just wanted to research it a little more since i'm not terribly familiar with everything. looks great.

**Comment by yeago** [comment]
@Jambazishvili oh, another thing, will this clear all filters on the, or just the one next to the reset?

**Comment by m3ck0** [comment]
It will clear fields related to filter widget itself, for sure.

**Pull request merged**
